name: learn-github-action-kubernates
run-name: ${{ github.actor }} is deploying to Kubernetes
on: [push]

jobs:
 push_to_registry:
  name: Push Docker image to Docker Hub
  runs-on: ubuntu-latest
  steps:
   - name: Check out the repo
     uses: actions/checkout@v4

   - name: Log in to Docker Hub
     uses: docker/login-action@v3
     with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_TOKEN }}

   - name: Build and push Docker image
     uses: docker/build-push-action@v5
     with:
      context: .
      file: ./Dockerfile
      push: true
      tags: ${{ secrets.DOCKER_USERNAME }}/api-${{ secrets.NIM }}:latest
 deploy_to_kubernetes:
  name: Deploy to Kubernetes
  runs-on: ubuntu-latest
  needs: push_to_registry
  steps:
   - name: Deploy to Kubernetes
     uses: indiesdev/curl@v1.1
     with:
      url: "http://154.26.139.201:8080/"
      method: "GET"
      headers: '{ "Content-Type": "application/json" }'
      response-code: 200
      log-response: true